/**
 * Generate the stylesheet Storybook renders against.
 *
 * Storybook must consume the SAME output a consuming app would, or it stops
 * being evidence. So this writes exactly two things, both from
 * `@bydiorama/tokens`: the `:root` token block (`toCss`) and the Tailwind
 * theme that maps utilities onto it (`toTailwindTheme`). Nothing here is
 * hand-authored — if a token changes, this file regenerates and every story
 * moves with it.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  resolveThemePair,
  toCss,
  toTailwindTheme,
  THEME_ZERO,
  ZERO_AUTHORED,
} from "@bydiorama/tokens";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../styles/tokens.generated.css");

const pair = resolveThemePair(THEME_ZERO, { authored: ZERO_AUTHORED });

const css = [
  "/* GENERATED by scripts/emit-css.ts — do not edit. */",
  "",
  toTailwindTheme(),
  "",
  toCss(pair, { scope: ":root", scheme: "auto" }),
].join("\n");

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css);
console.log(`wrote ${out.split("/ui/")[1]} (${css.split("\n").length} lines)`);
