/**
 * TypeScript-constants emitter.
 *
 * For contexts with no CSS custom-property resolution: email HTML (inline
 * styles only — no `var()`, no `light-dark()`), PDF/canvas rendering, chart
 * series colours. `toCss`/`toTailwindTheme` can point at a live variable and
 * let the cascade resolve it; this emitter cannot, so it resolves everything
 * itself and prints one scheme's literal values.
 *
 * The output is a flat `Record<token, value>` keyed by the same `--ui-*`
 * names the contract already uses — no invented nesting (`colors.primary`,
 * `textColors.muted`, …). A consumer's own convenience shape (the way
 * `tokenAdapters.ts` projects the legacy resolver's output onto
 * `EmailThemeTokens`/`TemplateBrandStyle`/a chart palette) is that
 * consumer's decision to make against real call sites, not this emitter's to
 * guess.
 */

import { BRANDABLE_TOKENS, SCHEME_ONLY_TOKENS, type BrandableToken, type SchemeOnlyToken } from "../contract.ts";
import { FIXED_TOKEN_VALUES, SCHEME_TOKEN_VALUES } from "../base.ts";
import type { ResolvedPair } from "../resolve.ts";

export type TsScheme = "light" | "dark";

export interface TsOptions {
  /** Which scheme's literal values to print. There is no `light-dark()`
   *  equivalent outside CSS, so the caller picks one up front. */
  scheme?: TsScheme;
  /** Name of the emitted `const`. */
  exportName?: string;
  indent?: string;
}

const VAR_REF = /var\((--ui-[\w-]+)\)/g;

/**
 * `FIXED_TOKEN_VALUES` aliases some entries onto others via `var(--ui-…)` —
 * real CSS, meaningless in a plain object. Substituted here, recursively
 * (`--ui-motion-micro` chains a duration AND an easing in one composite
 * string), bounded rather than trusted to terminate: a cycle in the token
 * table should fail loudly, not hang the build.
 */
function resolveInternalRefs(table: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = { ...table };
  for (let pass = 0; pass < 10; pass++) {
    let changed = false;
    for (const key of Object.keys(out)) {
      const value = out[key]!;
      if (!value.includes("var(")) continue;
      const next = value.replace(VAR_REF, (match, ref: string) => {
        if (!(ref in out)) {
          throw new Error(`toTsConstants: "${key}" references undefined token "${ref}"`);
        }
        return out[ref]!;
      });
      if (next !== value) {
        out[key] = next;
        changed = true;
      }
    }
    if (!changed) return out;
  }
  throw new Error("toTsConstants: var() references did not resolve within 10 passes — check for a cycle in FIXED_TOKEN_VALUES");
}

export function toTsConstants(pair: ResolvedPair, options: TsOptions = {}): string {
  const scheme = options.scheme ?? "light";
  const exportName = options.exportName ?? "tokens";
  const indent = options.indent ?? "  ";

  const resolvedFixed = resolveInternalRefs(FIXED_TOKEN_VALUES);

  const lines: string[] = [
    "/**",
    " * Generated by @bydiorama/tokens (emit/ts.ts). Do not hand-edit.",
    ` * Scheme: ${scheme}. For contexts with no CSS variable resolution —`,
    " * email HTML, PDF/canvas rendering, chart palettes.",
    " */",
    "",
    `export const ${exportName} = {`,
  ];

  const entries = (comment: string, obj: Record<string, string>) => {
    lines.push(`${indent}// ${comment}`);
    for (const [name, value] of Object.entries(obj)) {
      lines.push(`${indent}"${name}": ${JSON.stringify(value)},`);
    }
  };

  entries("Structural — identical in every theme and scheme.", resolvedFixed);

  const schemeOnly: Record<string, string> = {};
  for (const token of SCHEME_ONLY_TOKENS as readonly SchemeOnlyToken[]) {
    schemeOnly[token] = SCHEME_TOKEN_VALUES[token][scheme];
  }
  entries("Scheme-varying, brand-invariant.", schemeOnly);

  const branded: Record<string, string> = {};
  for (const token of BRANDABLE_TOKENS as readonly BrandableToken[]) {
    branded[token] = pair[scheme][token];
  }
  entries("Theme.", branded);

  lines.push("} as const;", "", `export type TsTokenName = keyof typeof ${exportName};`);

  return `${lines.join("\n")}\n`;
}
