/** Typed documentation for Toast (CONVENTIONS §11). */

export const toastDoc = {
  name: "Toast",
  status: "stable",
  summary:
    "A transient notification generated by the app, stacked bottom-right of the viewport. Built on Base UI Toast (ADR 0012): the queue, timers, stacking measurements, swipe gesture and announcement come from there; the API, anatomy and every pixel are the sheet's. Toasts collapse into a stack of three; hovering or focusing the viewport expands them.",

  anatomy: [
    { part: "viewport", slot: "toast-viewport", notes: "Fixed bottom-right, inset space-xl; width dialog-width-md capped to the viewport minus space-lg each side. A landmark region — F6 jumps to it — named by the required `label` prop." },
    { part: "root", slot: "toast", notes: "bg-elevated, a border-subtle hairline, radius-lg, shadow-lg. In dark the fill sits BELOW the page ground, so the hairline and shadow carry the boundary (ADR 0010). Height is clamped to the frontmost toast while collapsed." },
    { part: "content", slot: "toast-content", notes: "The padded row: p-lg, gap-md, overflow-hidden. Hidden (data-behind) while its toast is behind the front one; cross-fades back on expand." },
    { part: "icon", slot: "toast-icon", notes: "16px griddy glyph in a slot one title line tall (h-[1lh]), top-aligned so it centres on the first line however far the description wraps. Colour is the type's intent ink; the default type renders no icon. Loading renders Button's border-drawn spinner (slot toast-spinner)." },
    { part: "title", slot: "toast-title", notes: "16px bold in text-ink-primary. body-lg, NOT title-sm: the title roles are fluid (vw clamp) and a toast is a fixed 416px surface that does not follow the viewport — the browser test asserts the computed 16px." },
    { part: "description", slot: "toast-description", notes: "body-sm medium in text-ink-muted — Banner's message treatment. Carries the announcement when there is no title." },
    { part: "action", slot: "toast-action", notes: "Button — secondary · md, from `action: { label, onClick }`. At most one; pressing it runs onClick and then dismisses the toast." },
    { part: "close", slot: "toast-close", notes: "Banner's dismiss recipe: 24px hit area (SC 2.5.8) around a 16px Close glyph at full ink strength; hover tints the ground with currentColor at 10%. Named by the Viewport's required `dismissLabel`." },
  ],

  composition: `
Toast.Provider               limit? timeout?          — once, around the app
├─ <App/>                    anywhere below: useToast().add({ title, description, type, action })
└─ Toast.Viewport            label! dismissLabel! container?
   └─ (renders the stack — per-toast anatomy is not public API)
  `.trim(),

  props: {
    label: {
      type: "string",
      notes: "Required. Accessible name of the notifications landmark (the F6 target). A prop, not a default — every user-visible string is one (§9).",
    },
    dismissLabel: { type: "string", notes: "Required. Accessible name of every toast's close button." },
    container: {
      type: "HTMLElement | null",
      default: "document.body",
      notes: "Where the viewport is portalled. Theme tokens are INHERITED custom properties, so a viewport in the body leaves any brand scope on a wrapper and paints theme zero — pass the themed element to bring it back inside.",
    },
    limit: { type: "number", default: "3", notes: "Visible toasts before the oldest is hidden — kept mounted, inert, at opacity 0, so it can return if the stack shrinks." },
    timeout: { type: "number", default: "5000", notes: "Default auto-dismiss in ms; 0 never auto-dismisses. Paused while the viewport is hovered or focused and while the window is blurred (Base UI behaviour)." },
    "useToast()": {
      type: "() => ToastManager",
      notes: "add / close / update / promise, restated so no Base UI type reaches a consumer signature (ADR 0012). promise() runs one toast through loading → success/danger. add() with an existing id updates in place and resets the clock.",
    },
    type: {
      type: '"info" | "success" | "warning" | "danger" | "loading"',
      notes: "Omit for the plain, glyph-less toast. The glyph is the ONLY thing intent changes — the surface never tints, so a stack of mixed types does not read as a traffic light. `danger` is this library's name (shared with Banner/Button); Base UI's promise() stamps `error`, which renders identically.",
    },
    action: {
      type: "{ label: string; onClick: () => void }",
      notes: "Rendered as Button secondary · md through Base UI's actionProps, so screen readers hear it with the announcement. Runs onClick, then dismisses — an action that should keep the toast open belongs on a surface with room for it.",
    },
    priority: { type: '"low" | "high"', default: '"low"', notes: "low announces politely; high assertively — reserve it for danger. Only the title and description strings are announced, so keep both plain text." },
  },

  do: [
    "Mount one Provider + Viewport at the app root and fire everything through useToast() — twelve call sites want exactly this shape.",
    "Give the description the detail and keep the title to a few words; the description carries the announcement when there is no title.",
    "Use promise() for async work — one toast updates through loading → success/danger instead of three stacking up.",
    "Pass the themed element as `container` when the app wraps a brand scope around part of the page.",
  ],

  dont: [
    "Do not use a toast for a message that must be acknowledged — that is a Modal; or for one attached to a surface — that is a Banner.",
    "Do not set priority high for routine confirmations; an assertive announcement interrupts whatever the reader was in the middle of.",
    "Do not put a second action in a toast. One action plus Close is the whole vocabulary; more is a dialog.",
    "Do not import Base UI's Toast directly for custom internals — compose a request to design instead (the per-toast anatomy is deliberately not public API).",
  ],

  a11y: {
    role: "The viewport is a landmark region (Base UI), named by `label`; each toast announces via the manager's live region.",
    name: "Viewport: `label` (required). Close buttons: `dismissLabel` (required). Both required at the type level because an unnamed landmark and a nameless icon button are the two failures nothing visual ever catches.",
    keyboard: [
      { key: "F6", does: "Moves focus into the toast viewport; the stack expands and timers pause while focus is inside." },
      { key: "Tab", does: "Walks the focused toast's controls — action, then close." },
      { key: "Enter / Space", does: "Activates the focused control — native, both are real buttons." },
      { key: "Escape", does: "Closes the focused toast (Base UI behaviour; asserted in Chromium — F6, Tab into the toast, Escape, gone)." },
    ],
    contrastPairs: [
      { fg: "--ui-text-primary", bg: "--ui-bg-elevated", floor: "text", role: "the title — 15.53:1 light / 11.20:1 dark" },
      { fg: "--ui-text-muted", bg: "--ui-bg-elevated", floor: "text", role: "the description, the Close glyph and the loading spinner — 5.36:1 light / 5.78:1 dark" },
      { fg: "--ui-intent-info-fg", bg: "--ui-bg-elevated", floor: "non-text", role: "the info glyph — 5.39:1 light / 8.18:1 dark; the glyph is the only channel carrying the type (SC 1.4.11)" },
      { fg: "--ui-intent-success-fg", bg: "--ui-bg-elevated", floor: "non-text", role: "the success glyph — 5.62:1 light / 8.26:1 dark" },
      { fg: "--ui-intent-warning-fg", bg: "--ui-bg-elevated", floor: "non-text", role: "the warning glyph — 5.48:1 light / 7.23:1 dark" },
      { fg: "--ui-intent-danger-fg", bg: "--ui-bg-elevated", floor: "non-text", role: "the danger glyph — 5.38:1 light / 8.56:1 dark" },
      { fg: "--ui-bg-elevated", bg: "--ui-bg-base", floor: "decorative", role: "the toast against the page", why: "the boundary is the border-subtle hairline plus shadow-lg, not the fill (ADR 0010); in dark the fill sits below the page ground and the hairline is a 14%-alpha light line" },
    ],
    dismissal: "Timeout (paused on hover/focus/window blur), the Close button, Escape from within, or a swipe down/right. Toasts over the limit are hidden but stay mounted and inert rather than being destroyed under a screen reader.",
  },

  forwarding: {
    "Toast.Viewport": "className and remaining div props land on the viewport element (the outermost node this component owns). label → aria-label; dismissLabel is threaded to every toast's close button. No refs are exposed — there is no stable per-toast node to hold one on.",
  },

  motion:
    "Enter from translateY(150%) + fade; exit reverses toward the bottom edge, or along the swipe axis after a swipe. Transforms run duration-enter with ease-spring (the sheet's motion-choreographed pair), opacity on duration-slow, the stack's height settle on duration-fast — written as longhand transition properties because the split cannot be expressed in one shorthand. Behind-content cross-fades on duration-base. The loading spinner is animate-spin with the motion-reduce guard; every transition collapses under prefers-reduced-motion at the token layer.",

  needsDesign: [
    "Anchored toasts (Base UI's Toast.Positioner — transient 'Copied' chips on a trigger) are out of scope for the sheet and this component; they need their own design pass if a consumer asks.",
    "A shared Spinner primitive: loading reuses Button's private border-drawn spinner recipe for the third time. Three copies is the chrome-control story again.",
  ],

  knownGaps: [
    "The toast width reuses --ui-dialog-width-md (416px) — recorded as a Conflict on the sheet: if Toast should ever size independently of Modal, a --ui-toast-width token must be minted first.",
    "No global manager outside React (Base UI's createToastManager). All twelve measured call sites fire from components; add the wrapper when one does not.",
    "Exit-while-expanded uses the collapsed exit transform (the Base UI demo duplicates every ending transform under data-expanded; this component does not) — visible only when a toast times out at the exact moment the pointer is over the stack.",
    "swipeDirection is fixed to Base UI's default (down, right), matching the bottom-right placement; a viewport placement prop would need the sheet's Custom position pass first.",
  ],

  design: "https://app.paper.design/file/01KZ39A2BC286MT85M658NRR4R/4-0/2D9X-0",
} as const;

export type ToastDoc = typeof toastDoc;
